"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {sendImportedInvitation} from "@/features/account-imports/actions";
export type InvitationRow={id:string;username:string;first_name:string;last_name:string;email:string;role:string;status:string};
const labels:Record<string,string>={pending:"Ready to send",processing:"Delivery started · review if interrupted",sent:"Invited and linked",retry:"Rate limited · resume later",review:"Superadmin review needed"};
export function ImportDelivery({rows}:{rows:InvitationRow[]}){
 const router=useRouter(),running=useRef(false);const [busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[results,setResults]=useState<Record<string,{status:string;message:string}>>({});
 const pending=rows.filter(r=>["pending","retry"].includes(results[r.id]?.status??r.status));
 async function send(){if(running.current)return;running.current=true;setBusy(true);try{for(const [i,r] of pending.entries()){setProgress(`Sending invitation ${i+1} of ${pending.length}…`);const result=await sendImportedInvitation(r.id);if(result.status!=="configuration")setResults(prev=>({...prev,[r.id]:result}));if(result.status!=="sent"){setProgress(result.message);return;}}setProgress("Batch finished. Invitations accepted for delivery; inbox receipt is not confirmed.");}catch{setProgress("Processing stopped. Refresh and review the saved statuses before resuming.");}finally{running.current=false;setBusy(false);router.refresh();}}
 return <section className="space-y-4 rounded-xl border bg-white p-5" aria-busy={busy}><h2 className="text-lg font-semibold">Invitation delivery</h2><p className="text-sm text-muted">Keep this page open while sending. Progress is saved after each user. Pending rows can be resumed after reopening this batch. Interrupted or uncertain deliveries require superadmin review to avoid duplicate emails.</p><button type="button" className="rounded-lg bg-primary text-white px-4 py-2 disabled:opacity-50" disabled={busy||!pending.length} onClick={send}>{busy?"Sending invitations…":`Send pending invitations (${pending.length})`}</button><p role="status" aria-live="polite" className="text-sm">{progress}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["Name / username","Email","Role","Status"].map(h=><th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="p-2">{r.last_name}, {r.first_name}<br/><span className="text-muted">{r.username}</span></td><td className="p-2">{r.email}</td><td className="p-2">{r.role}</td><td className="p-2">{results[r.id]?.message??labels[r.status]??r.status}</td></tr>)}</tbody></table></div></section>;
}
