"use client";
import {useActionState,useState} from "react";
import {parseImport,type ImportRow} from "@/features/account-imports/schema";
import {prepareAccounts} from "@/features/account-imports/actions";
import {SubmitButton} from "@/components/ui/submit-button";
import {ActionFeedback} from "@/components/ui/feedback";
export function AccountImportForm({school}:{school:string}){
 const [csv,setCsv]=useState("");const [rows,setRows]=useState<ImportRow[]>([]);const [error,setError]=useState("");const [reading,setReading]=useState(false);const [state,action,pending]=useActionState(prepareAccounts,{});
 return <form action={action} aria-busy={pending||reading} className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Import school users</h2><p className="text-sm text-muted">Download the CSV template, fill it in using Excel or Google Sheets, then export as CSV. Maximum 100 users per upload. Email accepts Gmail and school email addresses. Usernames are school identifiers; users sign in with email.</p><a className="text-primary text-sm underline" href="/templates/user-import.csv" download>Download CSV template</a><p className="text-sm">Role values: TEACHER, ADVISER, STUDENT. Each row creates one role and a new teacher or student profile. Existing accounts must be connected separately by a superadmin. Class and subject assignments follow separately.</p><label className="block">Completed CSV<input type="file" accept=".csv,text/csv" disabled={pending||reading} onChange={async e=>{const f=e.target.files?.[0];setCsv("");setRows([]);setError("");if(!f)return;setReading(true);try{if(f.size>100_000)throw new Error("Use a CSV smaller than 100 KB.");const text=await f.text();const parsed=parseImport(text);setCsv(text);setRows(parsed);}catch(e){setError(e instanceof Error?e.message:"Could not read the file.");}finally{setReading(false);}}}/></label>
 <ActionFeedback pending={reading} error={error||undefined}/><input type="hidden" name="school" value={school}/><input type="hidden" name="csv" value={csv}/>
 {!!rows.length&&<><p role="status">{rows.length} users ready for review</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["Username","Last name","First name","Email","Role"].map(h=><th className="text-left p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.username}><td className="p-2">{r.username}</td><td className="p-2">{r.last_name}</td><td className="p-2">{r.first_name}</td><td className="p-2">{r.email}</td><td className="p-2">{r.role}</td></tr>)}</tbody></table></div><label className="flex gap-2 items-start"><input className="w-auto mt-1" key={csv} type="checkbox" name="confirmed" required/><span>I reviewed the names, emails and school roles. Create these profiles and prepare their invitations.</span></label></>}
 <ActionFeedback pending={pending} error={state.error}/><SubmitButton disabled={pending||reading||!rows.length} pendingLabel="Creating profiles…">Create users and prepare invitations</SubmitButton></form>;
}
