"use client";
import {useActionState,useState} from "react";
import {assignGrading} from "@/features/grading/actions";
import {SubmitButton} from "@/components/ui/submit-button";
import {ActionFeedback} from "@/components/ui/feedback";
import type {getAssessmentGrading} from "@/features/grading/queries";
export function AssessmentGradingForm({assessment,data,canManage}:{assessment:{id:string;version:number;published_at:string|null;assessment_date:string};data:Awaited<ReturnType<typeof getAssessmentGrading>>;canManage:boolean}){
 const [state,action,pending]=useActionState(assignGrading,{});const [scheme,setScheme]=useState(data.link?.scheme_id??"");
 const locked=!canManage||Boolean(assessment.published_at);
 return <section className="mt-5 bg-white border border-border rounded-lg p-5"><h3 className="font-semibold text-navy">Grading classification</h3><p className="text-sm text-muted mt-2">Choose an approved scheme for this school year. Classify assessments before publishing; published assessments are locked.</p><form action={action} aria-busy={pending} className="space-y-4 mt-4"><input type="hidden" name="target" value={assessment.id}/><input type="hidden" name="version" value={assessment.version}/><fieldset disabled={locked||pending} className="grid sm:grid-cols-3 gap-4"><div><label htmlFor="grading-scheme">Scheme</label><select id="grading-scheme" name="scheme" value={scheme} onChange={e=>setScheme(e.target.value)}><option value="">Not classified</option>{data.schemes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label htmlFor="grading-period">Period</label><select key={`period-${scheme}`} id="grading-period" name="period" required={!!scheme} defaultValue={data.link?.scheme_id===scheme?data.link.period_id:""}><option value="">Choose a period</option>{data.periods.filter(p=>p.scheme_id===scheme&&p.starts_on<=assessment.assessment_date&&p.ends_on>=assessment.assessment_date).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div><label htmlFor="grading-component">Component</label><select key={`component-${scheme}`} id="grading-component" name="component" required={!!scheme} defaultValue={data.link?.scheme_id===scheme?data.link.component_id:""}><option value="">Choose a component</option>{data.components.filter(c=>c.scheme_id===scheme).map(c=><option key={c.id} value={c.id}>{c.name} · {c.weight}%</option>)}</select></div></fieldset><ActionFeedback pending={pending} error={state.error} success={state.success}/>{!locked&&<SubmitButton pendingLabel="Saving classification…" disabled={pending}>Save grading classification</SubmitButton>}<p role="status" className="text-xs text-muted">{data.link?"Saved classification is shown above.":"No saved classification. No grading scheme is assumed."} Only periods containing the assessment date are available.</p></form></section>;
}
