"use client";
import {useActionState,useId,useState} from "react";
import {saveScheme,approveScheme} from "@/features/grading/actions";
import {ActionFeedback} from "@/components/ui/feedback";
import {SubmitButton} from "@/components/ui/submit-button";
import type {Database} from "@/lib/supabase/database.types";
type Tables=Database["public"]["Tables"];
export function SchemeForm({school,years,scheme,periods:initialPeriods,components:initialComponents}:{school:string;years:{id:string;name:string;starts_on:string;ends_on:string}[];scheme?:Tables["grading_schemes"]["Row"];periods:Pick<Tables["grading_periods"]["Row"],"name"|"starts_on"|"ends_on">[];components:Pick<Tables["grading_components"]["Row"],"name"|"weight">[]}){
 const id=useId();const [state,action,pending]=useActionState(saveScheme,{});const [approval,approve,approving]=useActionState(approveScheme,{});
 const [periods,setPeriods]=useState(initialPeriods.length?initialPeriods:[{name:"",starts_on:"",ends_on:""}]);
 const [components,setComponents]=useState(initialComponents.length?initialComponents.map(c=>({...c,weight:String(c.weight)})):[{name:"",weight:""}]);
 const [dirty,setDirty]=useState(false);const locked=Boolean(scheme?.approved_at);
 const total=components.reduce((n,c)=>n+Math.round(Number(c.weight)*100),0)/100;
 return <section className="border border-border rounded-lg bg-white p-5 space-y-4">
  <div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold text-navy">{scheme?.name??"New grading scheme"}</h3><span className="text-xs text-muted" role="status">{scheme?(locked?"Approved · Locked":`Draft · Saved version ${scheme.version}`):"Unsaved draft"}</span></div>
  <form action={action} aria-busy={pending} onChange={()=>setDirty(true)} className="space-y-4">
   <input type="hidden" name="school" value={school}/><input type="hidden" name="target" value={scheme?.id??""}/><input type="hidden" name="version" value={scheme?.version??0}/>
   <input type="hidden" name="periods" value={JSON.stringify(periods)}/><input type="hidden" name="components" value={JSON.stringify(components.map(c=>({...c,weight:Number(c.weight)})))}/>
   <fieldset disabled={locked||pending||approving} className="space-y-4">
    <div className="grid sm:grid-cols-2 gap-4"><div><label htmlFor={`${id}-name`}>Scheme name</label><input id={`${id}-name`} name="name" defaultValue={scheme?.name} required maxLength={100}/></div><div><label htmlFor={`${id}-year`}>School year</label><select id={`${id}-year`} name="year" defaultValue={scheme?.school_year_id??""} required><option value="">Choose a school year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name} ({y.starts_on} – {y.ends_on})</option>)}</select></div></div>
    <div><h4 className="text-sm font-semibold mb-2">Grading periods</h4><p className="text-xs text-muted mb-3">Dates must fit the school year and cannot overlap. Up to 12 periods.</p>{periods.map((p,i)=><div key={i} className="grid sm:grid-cols-4 gap-3 mb-3"><div><label htmlFor={`${id}-p${i}`}>Period {i+1}</label><input id={`${id}-p${i}`} required maxLength={60} value={p.name} onChange={e=>setPeriods(periods.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/></div><div><label htmlFor={`${id}-start${i}`}>Start date</label><input id={`${id}-start${i}`} type="date" required value={p.starts_on} onChange={e=>setPeriods(periods.map((v,j)=>j===i?{...v,starts_on:e.target.value}:v))}/></div><div><label htmlFor={`${id}-end${i}`}>End date</label><input id={`${id}-end${i}`} type="date" required value={p.ends_on} onChange={e=>setPeriods(periods.map((v,j)=>j===i?{...v,ends_on:e.target.value}:v))}/></div>{!locked&&<button type="button" className="text-sm text-primary self-end py-2" disabled={periods.length===1} onClick={()=>{setPeriods(periods.filter((_,j)=>j!==i));setDirty(true);}}>Remove period {i+1}</button>}</div>)}{!locked&&<button type="button" className="text-sm text-primary" disabled={periods.length>=12} onClick={()=>{setPeriods([...periods,{name:"",starts_on:"",ends_on:""}]);setDirty(true);}}>Add period</button>}</div>
    <div><h4 className="text-sm font-semibold mb-2">Components and weights</h4>{components.map((c,i)=><div key={i} className="grid sm:grid-cols-3 gap-3 mb-3"><div><label htmlFor={`${id}-c${i}`}>Component {i+1}</label><input id={`${id}-c${i}`} required maxLength={60} value={c.name} onChange={e=>setComponents(components.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/></div><div><label htmlFor={`${id}-w${i}`}>Weight (%)</label><input id={`${id}-w${i}`} type="number" required min="0.01" max="100" step="0.01" value={c.weight} onChange={e=>setComponents(components.map((v,j)=>j===i?{...v,weight:e.target.value}:v))}/></div>{!locked&&<button type="button" className="text-sm text-primary self-end py-2" disabled={components.length===1} onClick={()=>{setComponents(components.filter((_,j)=>j!==i));setDirty(true);}}>Remove component {i+1}</button>}</div>)}{!locked&&<button type="button" className="text-sm text-primary" disabled={components.length>=20} onClick={()=>{setComponents([...components,{name:"",weight:""}]);setDirty(true);}}>Add component</button>}<p aria-live="polite" className={`text-sm mt-3 ${total===100?"text-teal-800":"text-muted"}`}>Total: {Number.isFinite(total)?total:0}% · Approval requires exactly 100%.</p></div>
   </fieldset>
   <ActionFeedback pending={pending} error={state.error} success={state.success}/>
   {!locked&&<SubmitButton pendingLabel="Saving draft…" disabled={pending||approving||!years.length}>Save draft</SubmitButton>}
  </form>
  {scheme&&!locked&&<form action={approve} aria-busy={approving} className="border-t border-border pt-4 space-y-3"><input type="hidden" name="target" value={scheme.id}/><input type="hidden" name="version" value={scheme.version}/><label className="flex items-start gap-2 text-sm"><input type="checkbox" className="!w-4 mt-1" name="confirmed" required disabled={dirty||pending||approving}/>I reviewed the saved periods and weights. Approval locks this scheme.</label>{dirty&&<p className="text-xs text-muted">Save your changes before approving.</p>}<ActionFeedback pending={approving} error={approval.error} success={approval.success}/><SubmitButton pendingLabel="Approving…" disabled={dirty||pending||approving||total!==100}>Approve scheme</SubmitButton></form>}
  {locked&&<p className="text-xs text-muted">Approved {scheme!.approved_at!.slice(0,10)}. Create a new named scheme if your school needs different rules.</p>}
 </section>;
}
