import Link from "next/link";
import { ArrowRight, BookOpen, Users } from "lucide-react";
import type { Assignment } from "@/features/classes/types";
export function AssignmentList({ assignments }: { assignments: Assignment[]; }) {
 return <div className="bg-white border border-border rounded-lg overflow-hidden">
  <div className="px-5 py-4 flex items-center justify-between border-b border-border"><h2 className="font-semibold text-navy">Classes & assignments</h2><span className="text-xs text-muted">{assignments.length} assignments</span></div>
  {assignments.length ? <div className="overflow-x-auto"><table className="w-full"><caption className="sr-only">Your authorized classes and subjects</caption><thead><tr><th>Class / section</th><th>Subject</th><th>Responsibility</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{assignments.map(a => <tr key={a.id}><td><div className="font-medium whitespace-nowrap">{a.className}</div><div className="text-xs text-muted mt-1">{a.school} · {a.year}</div></td><td><div className="flex items-center gap-2"><span className={`text-[10px] font-semibold rounded px-1.5 py-1 ${a.kind === "Advisory" ? "bg-slate-100 text-slate-600" : "bg-[#eef0ff] text-[#4b46a6]"}`}>{a.code}</span><span className="whitespace-nowrap">{a.subject}</span></div></td><td><span className="flex items-center gap-1.5 text-xs text-muted whitespace-nowrap">{a.kind === "Advisory" ? <Users size={13} /> : <BookOpen size={13} />}{a.kind === "Advisory" ? "Class adviser" : "Subject access"}</span></td><td className="text-right"><Link aria-label={`Open ${a.subject}, ${a.className} roster`} href={`/teacher/classes/${a.id}`} className="text-primary text-xs font-semibold inline-flex items-center gap-2 whitespace-nowrap">Open roster <ArrowRight size={14} /></Link></td></tr>)}</tbody></table></div> : <div className="p-8 text-center"><p className="font-medium">No class assignments yet</p><p className="text-sm text-muted mt-2">Your school administrator can assign your subjects and classes.</p></div>}
 </div>;
}
