"use client";
import { useMemo, useState } from "react";
import { ArrowDownAZ, Search, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "./ui/button";
import type { RosterStudent } from "@/features/classes/types";
export function RosterTable({ students }: { students: RosterStudent[] }) {
 const [search, setSearch] = useState(""); const [descending, setDescending] = useState(false); const [page, setPage] = useState(0);
 const filtered = useMemo(() => students.filter(s => `${s.name} ${s.studentCode}`.toLocaleLowerCase().includes(search.toLocaleLowerCase().trim())).sort((a,b) => (descending ? -1 : 1) * a.name.localeCompare(b.name)), [students,search,descending]);
 const pageSize = 20, pages = Math.max(1,Math.ceil(filtered.length/pageSize));
 const currentPage = Math.min(page,pages-1); const rows = filtered.slice(currentPage*pageSize,(currentPage+1)*pageSize);
 return <section className="bg-white border border-border rounded-lg overflow-hidden">
  <div className="px-5 py-4 flex flex-wrap gap-4 items-center justify-between border-b border-border"><h2 className="font-semibold text-navy">Student roster <span className="ml-2 font-normal text-xs text-muted">{students.length} students</span></h2><div className="flex items-center gap-2 w-full sm:w-auto"><div className="relative flex-1 sm:w-64"><Search size={15} className="absolute left-3 top-3 text-muted" /><input className="!pl-9 !py-2 !text-xs" aria-label="Search students" placeholder="Search name or student ID" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></div><Button variant="outline" size="sm" aria-label={descending ? "Sort names ascending" : "Sort names descending"} onClick={() => {setDescending(!descending);setPage(0);}}><ArrowDownAZ size={15} />{descending ? "Z–A" : "A–Z"}</Button></div></div>
  <div className="overflow-auto max-h-[600px]"><table className="w-full"><caption className="sr-only">Students enrolled in this assignment</caption><thead className="sticky top-0 z-10"><tr><th className="w-16">No.</th><th aria-sort={descending ? "descending" : "ascending"}>Student name</th><th>Student ID</th><th>Enrollment</th></tr></thead><tbody>{rows.map((s,i) => <tr key={s.id}><td className="text-muted text-xs tabular-nums">{String(currentPage*pageSize+i+1).padStart(2,"0")}</td><td className="font-medium whitespace-nowrap">{s.name}</td><td className="font-mono text-xs text-muted whitespace-nowrap">{s.studentCode}</td><td><span className="inline-flex gap-1.5 items-center text-xs text-teal-800"><span className="w-1.5 h-1.5 rounded-full bg-teal-600" />Enrolled</span></td></tr>)}</tbody></table>{!rows.length && <div role="status" className="p-10 text-center"><p className="font-medium">{search ? "No students match your search" : "No students enrolled yet"}</p><p className="text-xs text-muted mt-2">{search ? "Try another name or student ID." : "Your school administrator can update this subject’s enrollment."}</p></div>}</div>
  <div className="px-5 py-3 border-t border-border flex items-center justify-between gap-3"><p aria-live="polite" className="text-xs text-muted">{filtered.length ? `${currentPage*pageSize+1}–${Math.min((currentPage+1)*pageSize,filtered.length)} of ${filtered.length} students` : "0 students"}</p><div className="flex gap-2 items-center text-xs text-muted"><span>Page {currentPage+1} of {pages}</span><Button variant="ghost" size="sm" aria-label="Previous page" disabled={currentPage===0} onClick={() => setPage(currentPage-1)}><ChevronLeft size={15} /></Button><Button variant="ghost" size="sm" aria-label="Next page" disabled={currentPage===pages-1} onClick={() => setPage(currentPage+1)}><ChevronRight size={15} /></Button></div></div>
 </section>;
}
