"use client";
import {useActionState,useId} from "react";
import {approveCalculation} from "@/features/grades/actions";
import {SubmitButton} from "@/components/ui/submit-button";
import {ActionFeedback} from "@/components/ui/feedback";
import type {Database} from "@/lib/supabase/database.types";
export function CalculationRule({scheme,rule}:{scheme:string;rule?:Database["public"]["Tables"]["grade_calculation_rules"]["Row"]}){
 const id=useId();const [state,action,pending]=useActionState(approveCalculation,{});
 return <section className="border border-border rounded-lg p-5 bg-white mt-3"><h3 className="font-semibold text-navy">School calculation rule</h3>
  {rule?<div role="status" className="text-sm mt-3 space-y-2"><p>Approved · {rule.method==="total_points"?"Total points within each component":"Equal assessment percentages within each component"}</p><p>Missing scores: {rule.missing_scores==="block"?"block submission":"count as zero"}. Final grade: {rule.decimal_places} decimal places.</p><p className="text-xs text-muted">This rule is locked. New calculation rules require a separately approved grading scheme.</p></div>:<>
   <p className="text-sm text-muted mt-2">Your school chooses the rule. Component weights come from the approved scheme; only the final percentage is rounded to the nearest value (half up).</p>
   <details className="text-sm mt-3"><summary className="cursor-pointer text-primary">Recommendations and calculation example</summary><div className="mt-3 space-y-2 text-muted"><p>Use total points when higher-point assessments should contribute more. Use average percentages when every assessment in a component should contribute equally.</p><p>Example: scores of 10/10 and 0/90 produce a component percentage of 10% with total points, or 50% with average percentages. The approved component weight is then applied.</p><p>We recommend requiring all scores and rounding the final percentage to two decimals. Choose zero for missing scores only when that is your school’s policy. A component with no assessments always blocks submission.</p></div></details>
   <form action={action} aria-busy={pending} className="space-y-4 mt-4"><input type="hidden" name="scheme" value={scheme}/><fieldset disabled={pending} className="grid sm:grid-cols-3 gap-4"><div><label htmlFor={`${id}-method`}>Calculation method</label><select id={`${id}-method`} name="method" required defaultValue=""><option value="">Choose a method</option><option value="total_points">Total earned / possible points</option><option value="average_percentages">Average assessment percentages</option></select></div><div><label htmlFor={`${id}-missing`}>Missing scores</label><select id={`${id}-missing`} name="missing_scores" required defaultValue=""><option value="">Choose school policy</option><option value="block">Require all scores</option><option value="zero">Count missing scores as zero</option></select></div><div><label htmlFor={`${id}-rounding`}>Final decimal places</label><select id={`${id}-rounding`} name="decimal_places" required defaultValue=""><option value="">Choose rounding</option><option value="0">0 — whole percentage</option><option value="1">1 decimal place</option><option value="2">2 decimal places</option></select></div></fieldset><label className="flex items-start gap-2 text-sm"><input className="!w-4 mt-1" name="confirmed" type="checkbox" required disabled={pending}/>I approve these calculation settings for this school’s grading scheme. Approval locks the rule.</label><ActionFeedback pending={pending} error={state.error} success={state.success}/><SubmitButton pendingLabel="Approving calculation…" disabled={pending}>Approve calculation rule</SubmitButton></form>
  </>}
 </section>;
}
