import Link from "@/components/ui/navigation-link";
import {getCompletion,completionStatuses} from "@/features/grades/completion";
export async function GradeCompletion({school,query,admin=false}:{school:string;query:{year?:string;page?:string;status?:string};admin?:boolean}){
 const {years,year,page,status,report}=await getCompletion(school,query);
 const url=(next:{year?:string;page?:number;status?:string}={})=>{const params=new URLSearchParams(admin?{school,tab:"completion"}:{school,view:"completion"});params.set("year",next.year??year?.id??"");params.set("page",String(next.page??0));params.set("status",next.status??status);return `${admin?"/deskonekt/admin":"/teacher"}?${params}`;};
 return <section className="space-y-5"><h2 className="text-xl font-semibold text-navy">Grade completion</h2><p className="text-sm text-muted">Track every configured subject period for the selected school year. All periods must be locked before this overview is complete; future periods are included.</p><nav aria-label="Completion school year" className="flex flex-wrap gap-3">{years.map(y=><Link key={y.id} className="text-sm text-primary" aria-current={y.id===year?.id?"page":undefined} href={url({year:y.id,status:""})}>{y.name}</Link>)}</nav>{!year&&<p className="text-muted">Add a school year before tracking grade completion.</p>}
  {report&&<><div role="status" className={`rounded-lg border p-4 text-sm ${report.ready?"bg-teal-50 border-teal-200 text-teal-900":"bg-amber-50 border-amber-200 text-amber-900"}`}>{report.ready?"All configured subject periods are locked.":"Grade completion is pending."} {report.unconfigured_subjects>0&&`${report.unconfigured_subjects} subjects have no fixed scheme yet. `}{report.empty_classes>0&&`${report.empty_classes} classes have no subject offerings. `}{report.total===0&&"No subject periods are available."}<p className="mt-2">This checks submission status only. It does not validate report cards, enrollment completeness or student release.</p></div>
  <nav aria-label="Filter completion status" className="flex flex-wrap gap-3"><Link className="text-sm border border-border rounded p-3" aria-current={!status?"page":undefined} href={url({status:""})}>All · {report.total}</Link>{completionStatuses.map(s=><Link key={s} aria-current={status===s?"page":undefined} className="text-sm border border-border rounded p-3 capitalize" href={url({status:s})}>{s} · {report.counts[s]}</Link>)}</nav>
  <p className="text-xs text-muted">Counts cover the entire school year. A subject without a fixed scheme counts once as Not submitted; its periods become known after the first submission.</p>
  <div className="overflow-auto border border-border rounded-lg bg-white"><table className="w-full text-sm"><caption className="sr-only">School grade completion</caption><thead><tr><th>Class</th><th>Subject</th><th>Period</th><th>Status</th><th>Revision</th><th>Details</th></tr></thead><tbody>{report.rows.map((r,i)=><tr key={i}><td>{r.class_name}</td><td>{r.subject}</td><td>{r.period_name??"Scheme not fixed"}</td><td className="capitalize">{r.status}</td><td>{r.revision??"—"}</td><td><Link className="text-primary" href={`/teacher/classes/${r.offering_id}?tab=grades${r.period_id?`&period=${r.period_id}`:""}`}>Open grades</Link></td></tr>)}</tbody></table>{!report.rows.length&&<p className="text-sm text-muted p-5">No records on this page for the selected filter.</p>}</div>
  <div className="flex gap-4 items-center text-sm"><span>Page {page+1} · {report.filtered_total} matching rows</span>{page>0&&<Link className="text-primary" href={url({page:page-1})}>Previous</Link>}{(page+1)*50<report.filtered_total&&<Link className="text-primary" href={url({page:page+1})}>Next</Link>}</div></>}
 </section>;
}
