"use client";
import {useActionState,useId,useState} from "react";
import {reviewGrades,resubmitGrades} from "@/features/grades/review-actions";
import {ActionFeedback} from "@/components/ui/feedback";
import {SubmitButton} from "@/components/ui/submit-button";
export function GradeReviewForm({target,version,token,resubmit=false,reviewed=false}:{target:string;version:number;token?:string;resubmit?:boolean;reviewed?:boolean}){
 const id=useId();const [decision,setDecision]=useState("returned");const [state,action,pending]=useActionState(resubmit?resubmitGrades:reviewGrades,{});
 return <form action={action} aria-busy={pending} className="border border-border rounded-lg bg-white p-5 space-y-4"><h3 className="font-semibold text-navy">{resubmit?"Review and resubmit":"Adviser review"}</h3><input type="hidden" name="target" value={target}/><input type="hidden" name="version" value={version}/><input type="hidden" name="token" value={token??""}/>{!resubmit&&<div><label htmlFor={`${id}-decision`}>Decision</label><select id={`${id}-decision`} name="decision" value={decision} onChange={e=>setDecision(e.target.value)} disabled={pending}><option value="returned">Return for correction</option>{!reviewed&&<option value="reviewed">Mark reviewed</option>}</select></div>}<div><label htmlFor={`${id}-reason`}>{resubmit?"What was corrected?":"Review reason / notes"}</label><textarea id={`${id}-reason`} name="reason" required={resubmit||decision==="returned"} maxLength={1000} rows={3} disabled={pending} className="w-full border border-border rounded-md p-3"/></div><p className="text-sm text-muted">{resubmit?"This creates a new submitted revision. Earlier snapshots and the adviser’s return reason remain in history.":"Returning enables teacher corrections. Marking reviewed records your review; it does not lock or release grades to students."}</p><label className="flex items-start gap-2 text-sm"><input name="confirmed" type="checkbox" className="!w-4 mt-1" required disabled={pending}/>I reviewed this version and confirm this action.</label><ActionFeedback pending={pending} error={state.error} success={state.success}/><SubmitButton pendingLabel="Saving…" disabled={pending}>{resubmit?"Resubmit period grades":"Save review decision"}</SubmitButton></form>;
}
