import { GradeReviewForm } from "./review-form";
import Link from "@/components/ui/navigation-link";
import {getPeriodGrades} from "@/features/grades/queries";
import {GradeSubmitForm} from "./submit-form";
export async function GradeWorkspace({offering,period,revision}:{offering:string;period?:string;revision?:string}){
 const data=await getPeriodGrades(offering,period,revision);const preview=data.preview;
 const base=`/teacher/classes/${offering}?tab=grades`;
 return <div className="space-y-5"><div><h2 className="text-xl font-semibold text-navy">Period grades</h2><p className="text-sm text-muted mt-2">Review calculated grades using your school’s approved calculation rule, then submit the period.</p></div>
  <nav aria-label="Choose grading period" className="flex flex-wrap gap-3">{data.options.map(p=><Link key={p.id} href={`${base}&period=${p.id}`} aria-current={period===p.id?"page":undefined} className={`text-sm border rounded-md px-3 py-2 ${period===p.id?"border-primary text-primary bg-purple-50":"border-border text-muted"}`}>{p.scheme_name} · {p.name}{data.history.find(h=>h.period_id===p.id)?` · ${data.history.find(h=>h.period_id===p.id)!.status}`:""}</Link>)}</nav>
  {!data.options.length&&<p className="text-muted">Your school must approve a grading scheme and its calculation rule for this school year before grades can be calculated.</p>}
  {!preview&&data.options.length>0&&<p className="text-muted">Choose a period to review grades.</p>}
  {data.submission&&<section className="border border-border rounded-lg p-4 space-y-3"><p role="status" className="font-medium">Status: {data.submission.status} · Latest revision {data.submission.revision}</p>{data.submission.return_reason&&<p className="text-sm text-amber-900">Adviser’s return reason: {data.submission.return_reason}</p>}<Link className="text-sm text-primary" href={`${base}&period=${period}`}>Current review / calculation</Link><details><summary className="cursor-pointer text-sm text-primary">Submission versions and review history</summary><ul className="space-y-2 mt-3 text-sm">{data.versions.map(v=><li key={v.revision}><Link className="text-primary" href={`${base}&period=${period}&revision=${v.revision}`}>View revision {v.revision}</Link> · {v.submitted_at.slice(0,10)}{v.correction_note&&` · ${v.correction_note}`}</li>)}</ul><ul className="space-y-2 mt-3 text-sm">{data.events.map(e=><li key={e.id}>Revision {e.revision} · {e.action} · {e.created_at.slice(0,10)}{e.reason&&` · ${e.reason}`}</li>)}</ul><p className="text-xs text-muted mt-2">Latest 50 versions and review events.</p></details></section>}
  {data.historical&&<p className="text-sm text-muted">Viewing historical revision {revision}. Return to the current review to take action.</p>}
  {preview&&<>
   <section className="bg-white rounded-lg border border-border p-5 space-y-2"><h3 className="font-semibold text-navy">{preview.scheme_name} · {preview.period_name}</h3><p className="text-sm text-muted">{preview.method==="total_points"?"Total earned points ÷ total possible points":"Average of assessment percentages"} within each component, multiplied by its approved weight. Only the final percentage is rounded to {preview.decimal_places} decimal places.</p><p className="text-sm text-muted">Missing scores {preview.missing_scores==="block"?"block submission":"count as zero under school policy"}. Calculations include saved draft and published assessment scores.</p>{data.submittedAt?<p role="status" className="text-sm text-teal-800">Submitted {new Date(data.submittedAt).toISOString().replace("T"," ").slice(0,19)} UTC · Fixed snapshot · Staff only</p>:<p className="text-sm text-muted">Live review · Save changes in assessment scores before reviewing here.</p>}</section>
   {!preview.ready&&<div role="alert" className="border border-amber-200 bg-amber-50 text-amber-900 p-4 rounded-lg text-sm">Submission is blocked. {preview.unclassified>0&&`${preview.unclassified} assessment(s) in this date range are unclassified or belong to another scheme/period. `}{!preview.students.length&&"No students are enrolled. "}Resolve missing scores required by school policy and components with no assessments.</div>}
   <div className="overflow-auto rounded-lg border border-border bg-white"><table className="w-full text-sm"><caption className="sr-only">Calculated period grades</caption><thead><tr><th>Student</th><th>Student ID</th><th>Grade (%)</th><th>Component breakdown</th></tr></thead><tbody>{preview.students.map(s=><tr key={s.id}><td>{s.display_name}</td><td>{s.student_code}</td><td>{s.grade===null?"Incomplete":s.grade.toFixed(preview.decimal_places)}</td><td><details><summary className="cursor-pointer text-primary">View {s.components.length} components</summary><ul className="space-y-2 mt-3">{s.components.map(c=><li key={c.id}>{c.name} ({c.weight}%): {c.earned}/{c.possible} points · {c.assessments} assessments · {c.missing} missing · Weighted contribution: {c.weighted===null?"Incomplete":`${c.weighted.toFixed(4)} percentage points`}<div className="text-xs text-muted mt-1">{c.scores.map(a=><span key={a.assessment_id} className="block">{a.title}: {a.score??"Missing"} / {a.max_score}</span>)}</div></li>)}</ul><p className="text-xs text-muted mt-2">Contributions are displayed to four decimals; final calculation uses full precision.</p></details></td></tr>)}</tbody></table></div>
   <details className="border border-border rounded-lg bg-white p-4"><summary className="cursor-pointer text-sm text-primary">Review {preview.assessments.length} source assessments</summary><ul className="mt-3 space-y-2 text-sm">{preview.assessments.map(a=><li key={a.id}><Link className="text-primary" href={`/teacher/classes/${offering}?tab=assessments&assessment=${a.id}`}>{a.title}</Link> · {a.assessment_date} · Out of {a.max_score} · {a.included?"Included":"Needs classification"} · Saved version {a.version}</li>)}</ul></details>
   {!data.historical&&data.submission&&data.canReview&&data.submission.status!=="returned"&&<GradeReviewForm reviewed={data.submission.status==="reviewed"} key={data.submission.review_version} target={data.submission.id} version={data.submission.review_version}/>}
   {!data.historical&&data.submission?.status==="returned"&&data.canSubmit&&preview.ready&&<GradeReviewForm key={`${data.submission.review_version}-${preview.token}`} target={data.submission.id} version={data.submission.review_version} token={preview.token} resubmit/>}
   {data.submittedAt?<p className="text-sm text-muted">Earlier submitted snapshots remain unchanged after corrections and resubmission.</p>:!data.submission&&data.canSubmit&&preview.ready?<GradeSubmitForm key={preview.token} offering={offering} period={preview.period_id} token={preview.token}/>:!data.canSubmit?<p className="text-sm text-muted">Only an assigned subject teacher can submit grades. Your access is read-only.</p>:null}
  </>}
 </div>;
}
