import Link from "@/components/ui/navigation-link";
import { ReportVersionForm } from "./version-form";
import {getReportCard} from "@/features/report-cards/queries";
import type {RosterStudent} from "@/features/classes/types";
import {ReportStudentPicker} from "./student-picker";
const labels={enrollment_review:"Subject enrollment needs review",scheme_missing:"Grading scheme not fixed",period_missing:"No grading periods configured",submission_missing:"Grades not submitted",not_locked:"Submission not locked",grade_missing:"Student grade missing or invalid in snapshot",grade_invalid:"Grade outside the supported percentage range",complete:"Locked grade available"};
export async function ReportCardWorkspace({classId,students,student,version}:{classId:string;students:RosterStudent[];student?:string;version?:string}){
 const data=student?await getReportCard(classId,student,version):null;
 const report=data?.report;
 const base=`/teacher/classes/advisory-${classId}?tab=report-cards&student=${student??""}`;
 return <section className="space-y-5"><div><h2 className="text-xl font-semibold text-navy">Report cards</h2><p className="text-sm text-muted mt-2">Staff-only school-year review. Each subject keeps its approved grading periods. Grades come from locked submission snapshots.</p></div><ReportStudentPicker classId={classId} students={students} selected={student}/>{!students.length&&<p className="text-muted">No students are enrolled in this class.</p>}
  {data&&<section className="space-y-3 border border-border rounded-lg p-4"><Link className="text-sm text-primary" href={base}>Open current preview</Link><p role="status" className="text-sm font-medium">{data.selected?`Saved version ${data.selected.version} · ${data.selected.approved_at?"Approved":"Awaiting approval"}`:"Live preview · Not saved"}</p>{data.selected&&<p className="text-xs text-muted">Saved {data.selected.saved_at.replace("T"," ").slice(0,19)} UTC{data.selected.approved_at&&` · Approved ${data.selected.approved_at.replace("T"," ").slice(0,19)} UTC`}</p>}{data.selected&&!data.sourceMatches&&<p role="alert" className="text-sm text-amber-900">This saved version no longer matches current grades or enrollment. It remains in history; save and review the current preview before a new approval.</p>}{data.selected&&data.selected.version!==data.record?.current_version&&<p className="text-sm text-muted">Historical version. Only the latest saved version can be approved.</p>}<details><summary className="text-sm text-primary cursor-pointer">Saved versions and approval history</summary><ul className="mt-3 space-y-2 text-sm">{data.versions.map(v=><li key={v.version}><Link className="text-primary" href={`${base}&report_version=${v.version}`}>Version {v.version}</Link> · {v.approved_at?"Approved":"Not approved"}</li>)}</ul><ul className="mt-3 space-y-2 text-xs text-muted">{data.events.map(e=><li key={e.id}>Version {e.version} · {e.action} · {e.created_at.replace("T"," ").slice(0,19)} UTC</li>)}</ul><p className="text-xs text-muted mt-3">Latest 50 saved versions and events.</p></details></section>}
  {report&&<><div role="status" className={`border rounded-lg p-4 text-sm ${report.ready?"border-teal-200 bg-teal-50 text-teal-900":"border-amber-200 bg-amber-50 text-amber-900"}`}>{report.ready?"Locked grades are complete for the configured subject enrollments.":report.total?`${report.incomplete} subject-period checks need attention.`:"No subject offerings are available for this student."}<p className="mt-2">{data?.selected?"This is a saved staff record, not a student-issued report card.":"This is the current live preview. Save a version for school approval."} Overrides and student release are not enabled.</p></div>
  <article className="bg-white border border-border rounded-lg overflow-hidden"><header className="p-5 border-b border-border"><p className="text-sm text-muted">{report.school} · {report.school_year}</p><h3 className="text-xl font-semibold text-navy mt-2">{report.student.name}</h3><p className="text-sm text-muted mt-2">{report.student.code} · {report.class.name}</p></header><div className="overflow-auto"><table className="w-full text-sm"><caption className="sr-only">School-year report-card completeness and locked grades</caption><thead><tr><th>Subject</th><th>Subject class</th><th>Scheme / period</th><th>Grade (%)</th><th>Check</th><th>Revision</th></tr></thead><tbody>{report.rows.map((r,i)=><tr key={i}><td>{r.subject}<span className="block text-xs text-muted">{r.code}</span></td><td>{r.subject_class}</td><td>{r.scheme_name??"—"}<span className="block text-xs text-muted">{r.period_name??"Period unknown"}{r.starts_on&&` · ${r.starts_on} to ${r.ends_on}`}</span></td><td>{r.grade??"—"}</td><td>{labels[r.check_status]}{r.submission_status&&r.check_status!=="complete"&&<span className="block text-xs text-muted">Submission: {r.submission_status}</span>}</td><td>{r.revision??"—"}</td></tr>)}</tbody></table></div></article>
  <p className="text-xs text-muted">Class subject offerings and the student’s independent subject enrollments in this school year are checked together. A class subject without enrollment requires staff review; it is not automatically added. No annual average or cross-subject weighting is assumed.</p>
  {data&&!data.selected&&!data.latestMatches&&<ReportVersionForm key={`${data.token}-${data.record?.current_version??0}`} classId={classId} student={student!} version={data.record?.current_version??0} token={data.token}/>}
  {data&&!data.selected&&data.latestMatches&&<p className="text-sm text-muted">This preview is already saved as version {data.record?.current_version}. Open that saved version to review its approval status.</p>}
  {data?.selected&&!data.selected.approved_at&&data.selected.version===data.record?.current_version&&data.sourceMatches&&report.ready&&(data.canApprove?<ReportVersionForm key={`${data.record.id}-${data.selected.version}`} classId={classId} student={student!} target={data.record.id} version={data.selected.version} token={data.selected.source_token} approve/>:<p className="text-sm text-muted">A school head or superadmin can approve this saved version.</p>)}
  </>}
 </section>;
}
