import {getReportCard} from "@/features/report-cards/queries";
import type {RosterStudent} from "@/features/classes/types";
import {ReportStudentPicker} from "./student-picker";
const labels={enrollment_review:"Subject enrollment needs review",scheme_missing:"Grading scheme not fixed",period_missing:"No grading periods configured",submission_missing:"Grades not submitted",not_locked:"Submission not locked",grade_missing:"Student grade missing or invalid in snapshot",grade_invalid:"Grade outside the supported percentage range",complete:"Locked grade available"};
export async function ReportCardWorkspace({classId,students,student}:{classId:string;students:RosterStudent[];student?:string}){
 const report=student?await getReportCard(classId,student):null;
 return <section className="space-y-5"><div><h2 className="text-xl font-semibold text-navy">Report-card preview</h2><p className="text-sm text-muted mt-2">Staff-only school-year review. Each subject keeps its approved grading periods. Grades come from locked submission snapshots.</p></div><ReportStudentPicker classId={classId} students={students} selected={student}/>{!students.length&&<p className="text-muted">No students are enrolled in this class.</p>}
  {report&&<><div role="status" className={`border rounded-lg p-4 text-sm ${report.ready?"border-teal-200 bg-teal-50 text-teal-900":"border-amber-200 bg-amber-50 text-amber-900"}`}>{report.ready?"Locked grades are complete for the configured subject enrollments.":report.total?`${report.incomplete} subject-period checks need attention.`:"No subject offerings are available for this student."}<p className="mt-2">This is a live preview, not an issued report card. Staff approval, overrides and student release are not enabled.</p></div>
  <article className="bg-white border border-border rounded-lg overflow-hidden"><header className="p-5 border-b border-border"><p className="text-sm text-muted">{report.school} · {report.school_year}</p><h3 className="text-xl font-semibold text-navy mt-2">{report.student.name}</h3><p className="text-sm text-muted mt-2">{report.student.code} · {report.class.name}</p></header><div className="overflow-auto"><table className="w-full text-sm"><caption className="sr-only">School-year report-card completeness and locked grades</caption><thead><tr><th>Subject</th><th>Subject class</th><th>Scheme / period</th><th>Grade (%)</th><th>Check</th><th>Revision</th></tr></thead><tbody>{report.rows.map((r,i)=><tr key={i}><td>{r.subject}<span className="block text-xs text-muted">{r.code}</span></td><td>{r.subject_class}</td><td>{r.scheme_name??"—"}<span className="block text-xs text-muted">{r.period_name??"Period unknown"}{r.starts_on&&` · ${r.starts_on} to ${r.ends_on}`}</span></td><td>{r.grade??"—"}</td><td>{labels[r.check_status]}{r.submission_status&&r.check_status!=="complete"&&<span className="block text-xs text-muted">Submission: {r.submission_status}</span>}</td><td>{r.revision??"—"}</td></tr>)}</tbody></table></div></article>
  <p className="text-xs text-muted">Class subject offerings and the student’s independent subject enrollments in this school year are checked together. A class subject without enrollment requires staff review; it is not automatically added. No annual average or cross-subject weighting is assumed.</p>
  </>}
 </section>;
}
