import {beforeEach,it,expect,vi} from "vitest";
const m=vi.hoisted(()=>({admin:vi.fn(),rpc:vi.fn(),invite:vi.fn()}));
vi.mock("@/features/admin/access",()=>({requireAdmin:m.admin}));
vi.mock("@supabase/supabase-js",()=>({createClient:()=>({auth:{admin:{inviteUserByEmail:m.invite}}})}));
vi.mock("next/cache",()=>({revalidatePath:vi.fn()}));
import {setupSchool} from "@/features/admin/onboarding";
const id="98000000-0000-4000-8000-000000000003",school="10000000-0000-4000-8000-000000000001";
function form(){const f=new FormData();Object.entries({request_id:id,school_name:"School",head_email:"head@school.test",first_name:"First",last_name:"Last",confirmed:"on"}).forEach(([k,v])=>f.set(k,v));return f;}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY","key");vi.stubEnv("NEXT_PUBLIC_SUPABASE_URL","https://example.supabase.co");vi.stubEnv("APP_URL","https://deskonekt.com");m.admin.mockResolvedValue({client:{rpc:m.rpc}});m.rpc.mockImplementation(async(name:string)=>({error:null,data:name==="prepare_school_onboarding"?{id,school_id:school,status:"pending"}:name==="claim_school_onboarding"?{status:"claimed",email:"head@school.test",first_name:"First",last_name:"Last"}:null}));m.invite.mockResolvedValue({data:{user:{id:"head-user"}},error:null});});
it("creates school, claims invitation, then links the head with only server-chosen role",async()=>{const result=await setupSchool({},form());expect(result.status).toBe("invited");expect(result.school_id).toBe(school);expect(m.rpc.mock.calls.map(c=>c[0])).toEqual(["prepare_school_onboarding","claim_school_onboarding","finish_school_onboarding"]);expect(m.invite).toHaveBeenCalledWith("head@school.test",{redirectTo:"https://deskonekt.com/auth/accept",data:{first_name:"First",last_name:"Last"}});expect(m.rpc).toHaveBeenLastCalledWith("finish_school_onboarding",{target:id,outcome:"invited",invited_user:"head-user"});});
it("does not email existing, completed or previously claimed setups",async()=>{for(const status of ["linked","invited","processing","review"]){m.rpc.mockResolvedValueOnce({data:{id,school_id:school,status},error:null}).mockResolvedValueOnce({data:{status},error:null});expect((await setupSchool({},form())).status).toBe(status);}expect(m.invite).not.toHaveBeenCalled();});
it("requires valid details, confirmation, configuration and superadmin access before creating schools",async()=>{const f=form();f.delete("confirmed");expect((await setupSchool({},f)).error).toContain("Confirm");expect(m.rpc).not.toHaveBeenCalled();f.set("confirmed","on");f.set("head_email","invalid");expect((await setupSchool({},f)).error).toContain("email");vi.stubEnv("APP_URL","");expect((await setupSchool({},form())).error).toContain("Configure");expect(m.rpc).not.toHaveBeenCalled();m.admin.mockRejectedValue(new Error("Denied"));await expect(setupSchool({},form())).rejects.toThrow("Denied");});
it("retains school details for rate limits and uncertain deliveries instead of recreating schools",async()=>{m.invite.mockResolvedValueOnce({data:{user:null},error:{status:429}});expect(await setupSchool({},form())).toMatchObject({school_id:school,status:"retry"});m.invite.mockRejectedValueOnce(new Error("network"));expect(await setupSchool({},form())).toMatchObject({school_id:school,status:"review"});});
it("does not claim success when role assignment fails after sending",async()=>{m.rpc.mockImplementation(async(name:string)=>({data:name==="prepare_school_onboarding"?{id,school_id:school,status:"pending"}:name==="claim_school_onboarding"?{status:"claimed",email:"head@school.test",first_name:"First",last_name:"Last"}:null,error:name==="finish_school_onboarding"?{code:"42501"}:null}));const result=await setupSchool({},form());expect(result.status).toBe("review");expect(result.error).toContain("role assignment");expect(result.school_id).toBe(school);});
